<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5e72b8b6a43bf',
	'title' => 'iLawyer Alert Bar Options',
	'fields' => array(
		array(
			'key' => 'field_5e72e29237ffb',
			'label' => 'Enable Alert Bar',
			'name' => 'onep21_enable_alert_bar',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Enabled',
			'ui_off_text' => 'Disabled',
		),
		array(
			'key' => 'field_5e72b8c748603',
			'label' => 'Alert Bar Text',
			'name' => 'onep21_alertbar_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Modify this text via the "iLawyer Alert Bar" options screen.',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
		),
		array(
			'key' => 'field_5e750809f944e',
			'label' => 'Styles',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e73e83156473',
			'label' => 'Preset Styles',
			'name' => 'onep21_preset_styles',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'custom' => '<b>Custom</b> - Create based on your own styles',
				'ilawyer' => 'Default <img src="/wp-content/plugins/1p21-alertbar/images/ilawyerdefault.jpg">',
				'canyon' => 'Canyon Sunset <img src="/wp-content/plugins/1p21-alertbar/images/canyonsunset.jpg">',
				'electric' => 'Electric <img src="/wp-content/plugins/1p21-alertbar/images/electric.jpg">',
				'graytemper' => 'Gray Tempered <img src="/wp-content/plugins/1p21-alertbar/images/graytempered.jpg">',
				'irishgold' => 'Irish Gold <img src="/wp-content/plugins/1p21-alertbar/images/irishgold.jpg">',
				'fine' => 'Everything\'s Fine <img src="/wp-content/plugins/1p21-alertbar/images/soundsfine.jpg">',
				'sospicy' => 'So Spicy <img src="/wp-content/plugins/1p21-alertbar/images/sospicy.jpg">',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'ilawyer',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5e72e0a85dcca',
			'label' => 'Alert Bar Styles',
			'name' => 'onep21_alertbar',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e73e83156473',
						'operator' => '==',
						'value' => 'custom',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key' => 'field_5e72e0e3d72dd',
					'label' => 'Background Color',
					'name' => 'background_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5e72e0f1d72de',
					'label' => 'Text Color',
					'name' => 'text_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5e72e111b5204',
					'label' => 'Hyperlink Color',
					'name' => 'hyperlink_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
			),
		),
		array(
			'key' => 'field_5e792a48d1a9b',
			'label' => 'Tablet & Mobile Position Bar Fixed At Bottom',
			'name' => 'onep21_fixed_bottom_mobile',
			'type' => 'true_false',
			'instructions' => 'This bar will overlay the bottom on Mobile & Tablet',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5e73c1cbaf268',
			'label' => '"Close" Button Style',
			'name' => 'onep21_close_btn_style',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e73e83156473',
						'operator' => '==',
						'value' => 'custom',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'text' => 'Text Button',
				'icon' => '<img src="/wp-content/plugins/1p21-alertbar/images/icon-close.svg" style="vertical-align:middle"> Icon',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5e72e15bcc245',
			'label' => 'Close Button Text',
			'name' => 'onep21_close_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e73c1cbaf268',
						'operator' => '==',
						'value' => 'text',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Close',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e72df31be440',
			'label' => 'Close Button Styles',
			'name' => 'onep21_close_btn',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e73c1cbaf268',
						'operator' => '==',
						'value' => 'text',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5e72df9d0ac77',
					'label' => 'Text Color',
					'name' => 'text_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5e72dfd8336fa',
					'label' => 'Button Background Color',
					'name' => 'background_color',
					'type' => 'color_picker',
					'instructions' => 'Default: Transparent',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5e741a4f800d9',
					'label' => 'Hover Text Color',
					'name' => 'hover_text',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5e73b48999068',
					'label' => 'Hover Background Color',
					'name' => 'background_hover_color',
					'type' => 'color_picker',
					'instructions' => 'Default: Transparent',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5e741cc488084',
					'label' => 'Border Width',
					'name' => 'border_width',
					'type' => 'number',
					'instructions' => 'Clear/Blank if no border',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => 'px',
					'min' => '',
					'max' => 5,
					'step' => 1,
				),
				array(
					'key' => 'field_5e72dff1336fb',
					'label' => 'Border Color',
					'name' => 'border_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e741cc488084',
								'operator' => '==',
								'value' => '1',
							),
						),
						array(
							array(
								'field' => 'field_5e741cc488084',
								'operator' => '>',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#2572ee',
				),
				array(
					'key' => 'field_5e741c9488083',
					'label' => 'Hover Border Color',
					'name' => 'border_hover_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e741cc488084',
								'operator' => '==',
								'value' => '1',
							),
						),
						array(
							array(
								'field' => 'field_5e741cc488084',
								'operator' => '>',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#2572ee',
				),
				array(
					'key' => 'field_5e73c6cd444d9',
					'label' => 'Rounded Corners?',
					'name' => 'border_radius',
					'type' => 'number',
					'instructions' => 'Clear if not rounded. Enter border-radius number',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => 'px',
					'min' => 0,
					'max' => 25,
					'step' => 1,
				),
			),
		),
		array(
			'key' => 'field_5e73cbb3a3b0e',
			'label' => '<img src="/wp-content/plugins/1p21-alertbar/images/icon-close.svg" style="vertical-align:middle"> Icon Styles',
			'name' => 'onep21_icon_styles',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e73c1cbaf268',
						'operator' => '==',
						'value' => 'icon',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key' => 'field_5e73cbd9a3b0f',
					'label' => 'Icon Color',
					'name' => 'color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#FFFFFF',
				),
				array(
					'key' => 'field_5e73cbeca3b10',
					'label' => 'Icon Hover Color',
					'name' => 'hover_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#FFFFFF',
				),
			),
		),
		array(
			'key' => 'field_5e7507a271190',
			'label' => 'Advanced Settings',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e72e553ab8d8',
			'label' => 'Cookie Expiration',
			'name' => 'onep21_cookie_expiration',
			'type' => 'number',
			'instructions' => 'Time in days that the alert bar will stay disabled after a user clicks the "close" button. Please half day increments (For Example: 1.5 = 32 hours or 1 1/2 days)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 1,
			'prepend' => '',
			'append' => 'Day(s)',
			'min' => '0.5',
			'max' => 30,
			'step' => '0.5',
		),
		array(
			'key' => 'field_5e791a9039b91',
			'label' => 'Inject JS Cookie to Footer',
			'name' => 'onep21_cookie_to_footer',
			'type' => 'true_false',
			'instructions' => 'Use this only if there isn\'t a valid \'jQuery" enqueue array on the site',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5e73c24e3eaa4',
			'label' => 'Custom CSS',
			'name' => 'onep21_custom_css',
			'type' => 'textarea',
			'instructions' => 'Add Custom CSS Code here to override any existing styles. Be sure to use proper syntax or this will break.<br>
<br>
Alert Bar ID/Classes<br>
#onep21-alertbar<br>
#onep21-alertbar p<br>
.onep21-alertbar-btn<br>
.onep21-close-icon <br>
.onep21-close-icon svg<br>',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5e750187feae8',
			'label' => 'Position Code',
			'name' => 'onep21_prepend',
			'type' => 'text',
			'instructions' => 'This will add the Alert Bar code to another div besides after the opening &lt;body&gt; tag. <br><br>
For example :<br>
-Type "header" (w/out apostrophes) if you want the bar code to be in &lt;header&gt;<br>
-Type ".header" for class="header or "#header" for id="header"',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'body',
			'placeholder' => 'body',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e7508721a301',
			'label' => 'Need to reposition an element using the Alert Bar\'s height?',
			'name' => 'onep21_use_dynamic_height',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5e7506a7de0ef',
			'label' => 'Add Dynamic Margin',
			'name' => 'onep21_dynamic_height',
			'type' => 'text',
			'instructions' => 'This will add "margin-top: (BarHeight)px" to reposition any "absolute" elements. <br><br>
For example :<br>
-Type "header" (w/out apostrophes) if you want "margin-top: (BarHeight)px" added to &lt;header&gt;<br>
-Type ".header" for class="header or "#header" for id="header"',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e7508721a301',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'alertbar-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;

?>